Add support for multiple semver tags
crazy-max/ghaction-docker-meta pull request #10
Opened 2020-11-04 19:15 UTC by fastlorenzo

This PR relates to issue #6 

If `full-semver` input is set to true, the action will try to parse the version tag (using `semver` package) and extract the `major`, `minor`, `patch` and `prerelease` components.

Example for input tag `v1.2.3-beta.4`, the following tags will be added:
- `v1`
- `v1.2`
- `v1.2.3`

Note that to add the prefix (`v` in this case), the following input option has been added as well: `semver-prefix` (in this case, it is equal to `v`)

2020-11-11 23:03 UTC, crazy-max requested changes

2020-11-11 23:03 UTC, crazy-max commented on __tests__/meta.test.ts
> +        'ghcr.io/user/app:v2.0.8',
`v2`, `v2.0` and `v2.0.8` tags should not be generated for pre-release. As explained in [semver specification](https://semver.org/) prerelease versions are updated frequently, and contain many breaking changes that are (by the author's design) not yet fit for public consumption.

2020-11-11 23:03 UTC, crazy-max commented on src/context.ts
> +    fullSemver: /true/i.test(core.getInput('full-semver') || 'false'),
```suggestion
    fullSemver: /true/i.test(core.getInput('full-semver')),
```

2020-11-11 23:04 UTC, crazy-max commented
And also update the relevant documentation.

2020-11-13 01:33 UTC, crazy-max commented
@fastlorenzo I thought a little bit more about the implementation and I think we should go through templating instead. I had been working on this via #3 and I think I'll put it back for your use case. The idea will be to improve this feature by using a list of versions that you want to assign as tags:

```yaml
    -
        name: Docker meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app
          tag-semver: |
            v{{major}}
            v{{major}}.{{minor}}
            v{{major}}.{{minor}}.{{patch}}
```

2020-11-13 06:22 UTC, fastlorenzo commented
Looks good to me as well, but what does it do when ref is not a valid semver (for example, using the same action to build container for a tag or for a push in a branch)?

2020-11-13 13:27 UTC, crazy-max commented
@fastlorenzo Will do nothing if it's not a valid semver.

2020-11-17 08:16 UTC, fastlorenzo commented
> 
> 
> @fastlorenzo Will do nothing if it's not a valid semver.

ok then I guess we can close this PR and go with your solution using `tag-semver` 😄

2020-11-17 22:31 UTC, closed without merging