Add tag flavor
crazy-max/ghaction-docker-meta pull request #15
Opened 2020-11-18 05:53 UTC by hugopeixoto

For cases where you have multiple flavors of the same container, like `node:12-alpine`, `node:12-debian`, etc, it would be nice to be able to specify these flavors in this github action. This was requested in #13.

Let's say that your container has two flavors, `debian` and `alpine`, and that you want images like `foo:latest` to be based on the debian flavor. You might want to generate these tags:

1. `foo:x.y.z-debian`
1. `foo:x.y.z-alpine`
1. `foo:x.y.z` (`= foo.x.y.z-debian`)
1. `foo:debian` (`= foo.x.y.z-debian`)
1. `foo:alpine` (`= foo.x.y.z-alpine`)
1. `foo:latest` (`= foo.x.y.z-debian`)
1. `foo:sha-AAAAAA-debian`
1. `foo:sha-AAAAAA-alpine`
1. `foo:sha-AAAAAA` (`= `foo:sha-AAAAAA-debian`)

To achieve this, I added two options: `flavor (string)` and `main-flavor (boolean)`. Trying to summarize their behavior:
- specifying a flavor will generate tags with the flavor suffix
- if no flavor is specified, or if there is a flavor but `main-flavor` is true, the flavorless tags will be emitted as well
- versionless flavorful tags (`foo:debian`) will only be generated if there's a flavor and the tag matches as `latest`.

In other words, each previously emited tag has its flavor counterpart:
- `foo:x.y.z` => `foo:x.y.z-{flavor}`
- `foo:latest` => `foo:{flavor}`
- `foo:sha-AAAAAA` => `foo:sha-AAAAAA-{flavor}`

And the left side are emited `if no flavor != '' or mainFlavor`, and the right side is emited `if flavor != ''`.

This is how I'm using this in a project:

```yaml
on:
  push:
    tags: '*.*.*'

jobs:
  release:
    strategy:
      matrix:
        base: [debian, alpine]
    steps:
      - uses:  hugopeixoto/ghaction-docker-meta@d08260d
        name: Docker meta
        id: docker_meta
        with:
          images: quay.io/hedgedoc/hedgedoc
          flavor: ${{ matrix.base }}
          main-flavor: ${{ matrix.base == 'debian' }}

```

I hope this is understandable :P Let me know what you think, and if this is an approach that makes sense. I wasn't sure if the `sha` tags should be flavored as well.

I still need to add tests and document this in the readme, but I'd like to know if this is something that you would consider integrate and iterate on before spending time there.

2020-11-24 21:57 UTC, crazy-max commented
@hugopeixoto Thanks for this PR. Can you merge please?

2020-11-25 17:52 UTC, hugopeixoto commented
> @hugopeixoto Thanks for this PR. Can you merge please?

I've rebased the PR to the latest master, resolving the conflicts. Let me know if you meant something else.

2020-11-25 18:02 UTC, crazy-max commented
@hugopeixoto Ahah my bad was tired yesterday, I meant rebase :sweat_smile:

2020-11-25 21:33 UTC, LongLiveCHIEF commented
@hugopeixoto you beat me to it.

2020-11-26 20:01 UTC, crazy-max requested changes
Overall LGTM but need some changes:

* Please don't create inline condition. We want to make sure code coverage is respected.
* Add tests
* Update README

2020-11-26 20:01 UTC, crazy-max commented on src/meta.ts
> +        if (hasFlavor) tags.push(`${imageLc}:sha-${this.context.sha.substr(0, 7)}-${flavor}`);
```suggestion
        if (main) {
          tags.push(`${imageLc}:sha-${this.context.sha.substr(0, 7)}`);
        }
        if (flavor) {
          tags.push(`${imageLc}:sha-${this.context.sha.substr(0, 7)}-${flavor}`);
        }
```

2020-11-30 14:50 UTC, yumetodo commented
I want to append suffix(like `-tesseract_opencv-4.5.0`). When this PR is merged, can I do that?

2020-12-01 13:50 UTC, LongLiveCHIEF commented
I suspect #24 may supersede this entirely, even though it may not have been intentionally designed to do so.

2020-12-01 15:14 UTC, crazy-max commented
@LongLiveCHIEF 

> I suspect #24 may supersede this entirely, even though it may not have been intentionally designed to do so.

Actually no, `tag-custom` add additional tags to those already produced and do not modify them as this PR does.

2020-12-01 22:27 UTC, hugopeixoto commented
I've updated the PR to include documentation in README.md and some tests in meta.test.ts.

@crazy-max I'm fighting codecov and losing. The current problem seems to be the line `let main = !flavor || this.inputs.mainFlavor;`, which is marked as partial, but I think I have the four cases covered. Could you help me figure out what's missing? The coverage report from `yarn test` doesn't seem to be as extensive as whatever codecov does.

2020-12-02 03:00 UTC, yumetodo commented
How about this? Some coverage tools cannot recognize short circuits correctly.

```ts
    let tags: Array<string> = [];
    const tagPush = (tagStr: string) => {
      if (this.inputs.flavor) {
        tags.push(`${tagStr}-${this.inputs.flavor}`);
        if (this.inputs.mainFlavor) {
          tags.push(tagStr);
        }
      } else {
        tags.push(tagStr);
      }
    };
    for (const image of this.inputs.images) {
      const imageLc = image.toLowerCase();
      tagPush(`${imageLc}:${this.version.main}`);
      for (const partial of this.version.partial) {
        tagPush(`${imageLc}:${partial}`);
      }
      if (this.version.latest) {
        if (this.inputs.flavor) {
          tags.push(`${imageLc}:${this.inputs.flavor}`);
          if (this.inputs.mainFlavor) {
            tags.push(`${imageLc}:latest`);
          }
        } else {
          tags.push(`${imageLc}:latest`);
        }
      }
      if (this.context.sha && this.inputs.tagSha) {
        tagPush(`${imageLc}:sha-${this.context.sha.substr(0, 7)}`);
      }
    }
```

2020-12-02 03:45 UTC, hugopeixoto commented
> How about this? Some coverage tools cannot recognize short circuits correctly.

Thanks for the suggestion. I tried a variation of that: instead of using `let main = x || y`, I tried this:

```typescript
if (flavor === '') {
  main = true;
} else if (this.inputs.mainFlavor) {
  main = true;
} else {
  main = false;
}
```

And each of the `main = true/false` lines is green (hit), but the if/else lines are yellow (partial). It seems like every `if` statement in this file is being marked as partial:
https://codecov.io/gh/crazy-max/ghaction-docker-meta/pull/15/src/src/meta.ts

Could it be that there's a problem with codecov's typescript tooling? I rolled the commit back to `!flavor || etc`.

2020-12-02 03:46 UTC, yumetodo commented
Oh...

2020-12-04 17:09 UTC, crazy-max commented
@hugopeixoto Yes don't worry with codecov for this kind of stuff, there's something wrong on their side about it or something needs to be configured on our side. Will check this out later.

2021-01-04 09:20 UTC, yumetodo commented
@crazy-max Do you have any updates? Are there any other problems?

2021-01-08 22:23 UTC, felbinger commented
Exactly the feature I need :+1:

2021-02-14 17:58 UTC, lpil commented
Hi @crazy-max , is there more to do here? 🙏

2021-03-15 17:24 UTC, crazy-max commented
@lpil Will focus on proposal in #30 and also work to drastically reduce the workflow by removing a maximum of inputs. I keep this PR opens for now as it provides a good use case.

2021-03-29 11:04 UTC, closed without merging